name: Run unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y build-essential libglib2.0-dev libxml2-dev libcunit1-dev libjansson-dev liblua5.3-dev valgrind
    - name: Clone apteryx
      uses: actions/checkout@v2
      with:
        repository: alliedtelesis/apteryx
        path: apteryx
    - name: Build Apteryx
      run: make -C ./apteryx
    - name: Clone apteryx-xml
      uses: actions/checkout@v2
      with:
        repository: alliedtelesis/apteryx-xml
        path: apteryx-xml
    - name: Build apteryx-xml
      run: APTERYX_PATH=../apteryx make -C ./apteryx-xml
    - name: Build apteryx-utils
      run: APTERYX_PATH=./apteryx APTERYX_XML_PATH=./apteryx-xml make
    - name: Run apteryxd
      run: LD_LIBRARY_PATH=./apteryx ./apteryx/apteryxd -b
    - name: Run Alfred unit tests
      run: LD_LIBRARY_PATH=./apteryx:./apteryx-xml:. G_SLICE=always-malloc valgrind --keep-debuginfo=yes --leak-check=full --error-exitcode=1 ./alfred -u
